update deploy scripts

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -58,13 +58,18 @@ then
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
+echo "We are currently at: "
+git rev-parse --abbrev-ref HEAD
+
 # Check if there are any uncommitted changes
 if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
     git diff-index --name-only HEAD --
     echo "Please commit the changes before proceeding."
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+    echo "We will stash the changes right now!"
+    git stash
+#    echo "Aborting."
+#    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Check if there are any untracked files
